---
- name: Installing MariaDB if it is base file
  hosts: all
  user: ansible
  vars_files:
    - vars/database.yml

  tasks:
  - name: Check if file {{ dbfile_path }} exists
    stat: path="{{ dbfile_path }}" 
    register: st

  - debug: msg="File {{ dbfile_path }} {{ 'exists' if st.stat.exists else 'does NOT exist' }}"

  - name: Installing mariadb-server
    yum: name=mariadb-server state=latest
    when: st.stat.exists
...
